trigger:
- develop
- master
- release/*
- hotfix/*

pr:
- develop
- release/*
- hotfix/*

jobs:
- job: Build
  pool:
    vmImage: 'windows-2022'
  steps:
  - task: Cache@2
    inputs:
      key: '"$(Agent.OS)" | recipe.cake'
      path: 'tools'
  - powershell: ./build.ps1
    displayName: 'Build'