trigger:
- develop
- master
- release/*
- hotfix/*

pr:
- develop
- release/*
- hotfix/*

jobs:
- job: Build
  pool:
    vmImage: 'windows-2022'
  steps:
  - task: Cache@2
    inputs:
      key: '"$(Agent.OS)" | recipe.cake'
      path: 'tools'
  # .NET 5 required for GitVersion
  - task: UseDotNet@2
    inputs:
      version: '5.x'
  - task: UseDotNet@2
    inputs:
      version: '6.x'
  - task: UseDotNet@2
    inputs:
      version: '7.x'
  - task: UseDotNet@2
    inputs:
      version: '8.x'
  - powershell: ./build.ps1
    displayName: 'Build'